In [1]:
import sys
import numpy as np
import pandas as pd
import importlib
sys.path.append('../')
from src.legacy.embedding_position_legacy import EmbeddingPosition
from src.embedding_trans import EmbeddingTrans
import src.markov_analysis
importlib.reload(src.markov_analysis)
from src.markov_analysis import Markov

/home/hugo/miniconda3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
df = pd.read_parquet('../data/toy_model/interim/phases_stereotypes2.parquet')
print(df.shape)
df.head()
emb_legacy = EmbeddingPosition(df,columns=[],columns_translated=['x','y','z'],ID_NAME='label',n_windows=10000)
emb = EmbeddingTrans(df,columns=[],columns_translated=['x','y','z'],ID_NAME='label',n_windows=10000)

(99700, 10)


In [3]:
emb.make_embedding(K=10)
emb.make_cluster(n_clusters=10)

(array([1, 1, 1, ..., 5, 5, 5], shape=(98800,)),
 array([[ 4.09303056e+00,  2.89733148e-03, -5.60180141e-02,
          3.26036090e+00, -1.03082328e-01, -1.71486879e-02,
          2.34935579e+00, -1.49544046e-01,  8.79842237e-03,
          1.40497510e+00, -9.02766461e-02,  1.61808507e-02,
          4.59591303e-01,  6.12004782e-02,  1.51958183e-02,
         -4.82416171e-01,  2.31357068e-01,  2.52247985e-02,
         -1.42936894e+00,  3.20315856e-01,  5.44833490e-02,
         -2.36568835e+00,  2.31627518e-01,  6.95905827e-02,
         -3.24956648e+00, -5.42707065e-02,  1.36876710e-02,
         -4.04027370e+00, -4.50224525e-01, -1.29994791e-01],
        [ 8.95012022e+00, -9.99214230e-03, -2.03193070e-03,
          6.99167322e+00, -2.61080199e-03, -1.65065540e-03,
          5.00198317e+00, -7.55342978e-04, -7.72835139e-04,
          3.00053308e+00,  1.87580092e-03,  5.06139501e-04,
          1.00084562e+00,  3.92009103e-03,  1.40098741e-03,
         -9.98656080e-01,  6.76913026e-03,  8.6541

In [4]:
emb_legacy.make_embedding(K=10)
emb_legacy.make_cluster(n_clusters=10)

(array([1, 1, 1, ..., 5, 5, 5], shape=(98800,)),
 array([[ 4.09303056e+00,  2.89733148e-03, -5.60180141e-02,
          3.26036090e+00, -1.03082328e-01, -1.71486879e-02,
          2.34935579e+00, -1.49544046e-01,  8.79842237e-03,
          1.40497510e+00, -9.02766461e-02,  1.61808507e-02,
          4.59591303e-01,  6.12004782e-02,  1.51958183e-02,
         -4.82416171e-01,  2.31357068e-01,  2.52247985e-02,
         -1.42936894e+00,  3.20315856e-01,  5.44833490e-02,
         -2.36568835e+00,  2.31627518e-01,  6.95905827e-02,
         -3.24956648e+00, -5.42707065e-02,  1.36876710e-02,
         -4.04027370e+00, -4.50224525e-01, -1.29994791e-01],
        [ 8.95012022e+00, -9.99214230e-03, -2.03193070e-03,
          6.99167322e+00, -2.61080199e-03, -1.65065540e-03,
          5.00198317e+00, -7.55342978e-04, -7.72835139e-04,
          3.00053308e+00,  1.87580092e-03,  5.06139501e-04,
          1.00084562e+00,  3.92009103e-03,  1.40098741e-03,
         -9.98656080e-01,  6.76913026e-03,  8.6541

In [5]:
mkv_legacy = Markov(emb_legacy,tau=1)

In [6]:
mkv = Markov(emb,tau=1)

In [8]:
mkv.P - mkv_legacy.P

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
embedding_shape = np.zeros(emb.embedding_matrix.__len__(),dtype=int)
for idx in range(embedding_shape.__len__()):
    embedding_shape[idx] = emb.embedding_matrix[idx-1].shape[0]
reshaped_labels = list()
idx = 0
for n in range(embedding_shape.shape[0]):
    print(idx)
    print(idx+embedding_shape[n])
    reshaped_labels.append(emb.labels[idx:idx+embedding_shape[n]])
    idx += embedding_shape[n]

0
988
988
1976
1976
2964
2964
3952
3952
4940
4940
5928
5928
6916
6916
7904
7904
8892
8892
9880
9880
10868
10868
11856
11856
12844
12844
13832
13832
14820
14820
15808
15808
16796
16796
17784
17784
18772
18772
19760
19760
20748
20748
21736
21736
22724
22724
23712
23712
24700
24700
25688
25688
26676
26676
27664
27664
28652
28652
29640
29640
30628
30628
31616
31616
32604
32604
33592
33592
34580
34580
35568
35568
36556
36556
37544
37544
38532
38532
39520
39520
40508
40508
41496
41496
42484
42484
43472
43472
44460
44460
45448
45448
46436
46436
47424
47424
48412
48412
49400
49400
50388
50388
51376
51376
52364
52364
53352
53352
54340
54340
55328
55328
56316
56316
57304
57304
58292
58292
59280
59280
60268
60268
61256
61256
62244
62244
63232
63232
64220
64220
65208
65208
66196
66196
67184
67184
68172
68172
69160
69160
70148
70148
71136
71136
72124
72124
73112
73112
74100
74100
75088
75088
76076
76076
77064
77064
78052
78052
79040
79040
80028
80028
81016
81016
82004
82004
82992
82992
83980
83980


In [6]:
emb.N

100

In [7]:
def count_transitions_1(labels: np.ndarray, n_clusters: int, tau: int) -> np.ndarray:
    """
    Return the raw transition count matrix C (without normalisation).
    Notice that we do not concatenate the pieces of trajectories one after the other
    to avoid unrealistic transition
    
    nsample: the number of trajectories
    TmKp1 : T - K +1
    """
    C = np.zeros((n_clusters, n_clusters), dtype=float)
    for trajectory in labels:
        for t in range(trajectory.shape[0] - tau):
            i,j = trajectory[t],trajectory[t+tau]
            C[i,j] += 1
    return C
def count_transitions(labels: np.ndarray, n_clusters: int, tau: int, nsample: int, TmKp1: int) -> np.ndarray:
    """
    Return the raw transition count matrix C (without normalisation).
    Notice that we do not concatenate the pieces of trajectories one after the other
    to avoid unrealistic transition
    
    nsample: the number of trajectories
    TmKp1 : T - K +1
    """
    C = np.zeros((n_clusters, n_clusters), dtype=float)
    for n in range(nsample):            
        for start in range(TmKp1 - tau):
            i, j = labels[n*TmKp1+start], labels[n*TmKp1+start + tau]
            C[i, j] += 1.0
    return C

In [8]:
#from src.trajectory_utils import count_transitions
C1 = count_transitions(emb.labels,emb.n_clusters,1,emb.N,emb.T-emb.K+1)
C2 = count_transitions_1(reshaped_labels,emb.n_clusters,1)

In [10]:
C2

array([[1.0989e+04, 0.0000e+00, 2.9000e+01, 1.6000e+01, 0.0000e+00,
        4.7370e+03, 0.0000e+00, 0.0000e+00, 1.3210e+03, 1.5000e+01],
       [0.0000e+00, 2.8086e+04, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 6.4000e+02, 0.0000e+00, 0.0000e+00, 2.0000e+00],
       [6.2100e+02, 0.0000e+00, 4.1870e+03, 0.0000e+00, 0.0000e+00,
        2.4700e+03, 0.0000e+00, 3.3000e+01, 3.1500e+02, 1.8400e+02],
       [0.0000e+00, 0.0000e+00, 4.4000e+01, 2.0600e+02, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 3.2700e+02, 0.0000e+00, 0.0000e+00],
       [1.7000e+01, 0.0000e+00, 4.5000e+01, 1.8300e+02, 2.7900e+02,
        1.2900e+02, 0.0000e+00, 1.0000e+00, 1.3400e+02, 1.5000e+01],
       [5.3910e+03, 0.0000e+00, 8.5000e+01, 0.0000e+00, 0.0000e+00,
        2.3198e+04, 0.0000e+00, 0.0000e+00, 2.1350e+03, 1.3900e+02],
       [4.0000e+00, 8.0000e+00, 0.0000e+00, 0.0000e+00, 5.2400e+02,
        0.0000e+00, 7.2900e+02, 0.0000e+00, 0.0000e+00, 1.0400e+02],
       [6.8000e+01, 0.0000e+00, 1.8400e+0